# Generated by Django 2.1.1 on 2020-11-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=25)),
                ('state', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('hospital', models.CharField(default='', max_length=50)),
                ('patient_id', models.CharField(max_length=25)),
                ('date', models.DateField(null=True)),
                ('age', models.CharField(default='', max_length=50)),
                ('sex', models.CharField(default='', max_length=50)),
                ('sample', models.CharField(default='', max_length=50)),
                ('department', models.CharField(default='', max_length=50)),
                ('examination_date', models.DateTimeField(null=True)),
                ('requi_date', models.DateTimeField(null=True)),
                ('report_date', models.DateTimeField(null=True)),
                ('sample_collection_datetime', models.DateTimeField(null=True)),
                ('allergy', models.IntegerField(default=0)),
                ('symptoms', models.CharField(default='', max_length=50)),
                ('diagnosis', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
