ORGANISMS = [   'Achromobacter denitrificans',
                'Acinetobacter aeruginosa',
                'Acinetobacter baumannii',
                'Acinetobacter lwoffii',
                'Acinetobacter sp.',
                'Aeromonas sp.',
                'Alcaligenes faecalis',
                'Budding yeast',
                'Burkholderia cenocepacia',
                'Burkholderia cepacia',
                'Burkholderia sp.',
                'Chryseobacterium indologenes',
                'Citrobacter diversus',
                'Citrobacter edialai',
                'Citrobacter freundii',
                'Citrobacter koseri',
                'Citrobacter sp.',
                'Coagulase-negative staphylococci',
                'Commensal-flora',
                'Elizabethkingia meningoseptica',
                'Enterobacter',
                'Enterobacter aerogenes',
                'Enterobacter-cloacae',
                'Enterobacteriaceae',
                'Enterococcus',
                'Enterococcus faecalis',
                'Escherichia coli',
                'Gram-negative ',
                'Klebsiella-oxytoca',
                'Klebsiella-pneumoniae',
                'Klebsiella-species',
                'Morganella-morganii',
                'Neisseria-gonorrhoeae',
                'Proteus mirabilis',
                'Proteus sp',
                'Proteus vulgaris',
                'Providencia',
                'Pseudomonas aeruginosa',
                'Pseudomonas fluorescens',
                'Pseudomonas putida',
                'Salmonella-paratyphi',
                'Salmonella-typhimurium',
                'Serratia-marcescens',
                'Shewanella-putrefaciens',
                'Staph-haemolyticus',
                'Staphylococcaceae',
                'Staphylococcal-pneumonia',
                'Staphylococcus',
                'staphylococcus aureus mrsa',
                'Staphylococcus-aureus',
                'Staphylococcus-capitis',
                'Staphylococcus-epidermidis',
                'Staphylococcus-haemolyticus',
                'Staphylococcus-hominis',
                'Staphylococcus-lugdunensis',
                'Staphylococcus-mssa',
                'Staphylococcus-schleiferi',
                'Staphylococcus-simulans',
                'Stenotrophomonas-maltophilia',
                'Streptococcus ',
                'Viridans streptococci',
                'Yeast']