ORGANISMS = [' Enterococcus faecalis',
             ' Klebsiella-oxytoca',
             ' Pseudomonas putida',
             'Achromobacter denitrificans',
             'Acinetobacter baumannii',
             'Acinetobacter lwoffii',
             'Acinetobacter sp.',
             'Aeromonas sp.',
             'Burkholderia cenocepacia',
             'Burkholderia cepacia',
             'Burkholderia sp.',
             'Chryseobacterium indologenes',
             'Citrobacter diversus',
             'Citrobacter freundii',
             'Citrobacter koseri',
             'Citrobacter sp.',
             'Coagulase-negative staphylococci',
             'Commensal-flora',
             'Elizabethkingia meningoseptica',
             'Enterobacter',
             'Enterobacter aerogenes',
             'Enterobacter-cloacae',
             'Enterobacteriaceae',
             'Enterococcus',
             'Enterococcus faecium',
             'Enterococcus-faecium',
             'Escherichia coli',
             'Gram-negative ',
             'Klebsiella-oxytoca',
             'Klebsiella-pneumoniae',
             'Klebsiella-species',
             'Mixed growth',
             'Morganella-morganii',
             'Neisseria-gonorrhoeae',
             'Proteus mirabilis',
             'Proteus sp',
             'Proteus vulgaris',
             'Providencia',
             'Pseudomonas aeruginosa',
             'Pseudomonas fluorescens',
             'Salmonella-paratyphi',
             'Salmonella-typhimurium',
             'Serratia-marcescens',
             'Shewanella-putrefaciens',
             'Staph-haemolyticus',
             'Staphylococcaceae',
             'Staphylococcal-pneumonia',
             'Staphylococcus',
             'Staphylococcus-aureus',
             'Staphylococcus-capitis',
             'Staphylococcus-epidermidis',
             'Staphylococcus-haemolyticus',
             'Staphylococcus-hominis',
             'Staphylococcus-lugdunensis',
             'Staphylococcus-mssa',
             'Staphylococcus-schleiferi',
             'Staphylococcus-simulans',
             'Stenotrophomonas-maltophilia',
             'Streptococcus ',
             'citrobacter edialai',
             'staphylococcus aureus mrsa',
             'viridans streptococci',
             '\u202b\u202aEntro coccus faecalis']
