COLLTYPES = [   'Ascitic fluid',
                'Aspirate',
                'Bile',
                'Biopsy',
                'Blood',
                'Bone',
                'Bone marrow',
                'Broncho-Alveolar Lavage',
                'Catheter tip',
                'Cervical Discharge',
                'Continuous ambulatory peritoneal dialysis',
                'CSF',
                'CVP tip',
                'Drain fluid',
                'Endotracheal aspirate',
                'Epidural tip',
                'EVD tip',
                'Gastric aspirate',
                'Graft',
                'High Vaginal Swab',
                'Implants and grafts',
                'Nasal crust',
                'Nasal swap',
                'Nasopharyngeal aspirate',
                'Oral swab',
                'Others',
                'PCN (Left)',
                'PCN (Right)',
                'Pericardial fluid',
                'Peritoneal fluid',
                'Pigtail fluid',
                'Placenta',
                'Pleural fluid',
                'Prostatic secretion',
                'Prosthetics / Implants',
                'Pus',
                'Rectal swab',
                'Semen',
                'Shunt Chamber',
                'Shunts',
                'Sputum',
                'Stem cell',
                'Sterile body fluid',
                'Stone',
                'Stool',
                'Suction catheter tip',
                'Susceptiblity test',
                'Synovial fluid',
                'Throat swab',
                'Tissue',
                'Tracheal aspirate',
                'Trachostomy tip',
                'Urethral Discharge',
                'Urine',
                'Vaginal Discharge',
                'Valve',
                'Wound swab']