COLLTYPES = ['Ascitic fluid',
             'Aspirate',
             'Bile',
             'Biopsy',
             'Blood',
             'Bone',
             'Bone marrow',
             'Broncho-Alveolar Lavage',
             'CSF',
             'CVP tip',
             'Catheter tip',
             'Cervical Discharge',
             'Drain fluid',
             'Endotracheal aspirate',
             'Graft',
             'High Vaginal Swab',
             'Implants and grafts',
             'Nasal crust',
             'Nasopharyngeal aspirate',
             'Oral swab',
             'Others',
             'PCN',
             'Pericardial fluid',
             'Peritoneal fluid',
             'Pigtail fluid',
             'Placenta',
             'Pleural fluid',
             'Prostatic secretion',
             'Prosthetics / Implants',
             'Pus',
             'Rectal swab',
             'Semen',
             'Shunt Chamber',
             'Shunts',
             'Sputum',
             'Stem cell',
             'Sterile body fluid',
             'Stone',
             'Stool',
             'Suction catheter tip',
             'Synovial fluid',
             'Throat swab',
             'Tissue',
             'Tracheal aspirate',
             'Trachostomy tip',
             'Urethral Discharge',
             'Urine',
             'Vaginal Discharge',
             'Valve',
             'Wound swab']
