SITES = ['1A',
         '1B',
         '2A',
         '2B',
         '3A',
         '3B',
         '4A',
         'AB1',
         'AB1-PACU',
         'AB2',
         'AB2-ICU',
         'AB3',
         'AB4',
         'AB4-Dialysis',
         'AB5',
         'AB5-ICU',
         'AB6',
         'AB7',
         'AB7-KTP',
         'AB7-PAR',
         'AB8',
         'AB8-ICU',
         'C1',
         'C2',
         'C2-ICU',
         'C3-LR',
         'C3-LR-New Born',
         'C3-NICU-A',
         'C4',
         'C5',
         'C5-Day Care',
         'C6-Emergency',
         'C6-Miscellaneous',
         'C7',
         'CDER',
         'CNT-1',
         'CNT-2',
         'CNT-3',
         'CNT-4',
         'CNT-5',
         'CNT-6',
         'CT-2-CCU',
         'CT-3',
         'CT-4',
         'CT-5',
         'CT-6',
         'CTVS-ICU-A',
         'CTVS-OT3',
         'CTVS-OT7',
         'CTVS-OT8',
         'D1',
         'D1-Day Care',
         'D2',
         'D3',
         'D3-FMOT',
         'D4',
         'D5',
         'D5-Dialysis',
         'D5-ICU',
         'D6-Emergency',
         'D6-G.I.Surgery',
         'D6-ICU',
         'D6-Miscellaneous',
         'D7',
         'D7-HDU',
         'EBM-OT',
         'GMW-Geriatic Medicine Ward',
         'Hematology-Day Care',
         'IRCH-BMT-Unit Ward',
         'IRCH-Day Care',
         'IRCH-ICU',
         'IRCH-MO Ward',
         'IRCH-MRO Ward',
         'IRCH-PCU',
         'IRCH-Private Ward',
         'IRCH-RT Ward',
         'IRCH-Surgical Ward-5F',
         'IRCH-Surgical Ward-FF',
         'KMC',
         'MAIN-OT',
         'MAT-OT',
         'MCU',
         'Minor-OT-Orthology',
         'Minor-OT-Urology',
         'NCI-Emergency Ward',
         'NCI-I Floor ',
         'NDDTC-Ward A',
         'NDDTC-Ward B',
         'NEW-EMW',
         'NICU-B1',
         'NICU-B2',
         'NPW-Ground Floor',
         'NPW-I Floor',
         'NPW-II Floor',
         'NPW-III Floor',
         'NS-2',
         'NS-3',
         'NS-4',
         'NS-5',
         'NS-ICU-A',
         'NS-ICU-B',
         'NS-ICU-C',
         'NS4-VEEG',
         'NSOT',
         'OPW-I FLOOR',
         'OPW-II FLOOR',
         'OPW-III FLOOR',
         'OPW-IV FLOOR',
         'OPW-V FLOOR',
         'PMW-ICU',
         'Pulmonary-Medicine Ward',
         'RPC-Day Care .',
         'RPC-Private Ward-III',
         'Rheumatology']
